### PR TITLE
Revert "Reorganization of the CI"

### PR DESCRIPTION
**Pull request by gtribello**
Reverts plumed-school/plumed-school#4

### CODE REVIEW

**Comment by Iximiel** [comment]
@gtribello I do not understand: in #4 I did not touch "build_manual.py" that is the reason of the failure of the CI
I think that the failure is due to the fact that at the moment of writing this "https://www.plumed-tutorials.org/summary.html" is a 404

**Comment by gtribello** [comment]
Whatever you did totally messed up the build of the website.  Open it now.  Many pages (e.g. browse.md and summary.md) are just not copied to the website repo.  The links thus appear broken.

`build_manual.py` tries to read some of the pages from the website that are no longer there, which is why it messes up.

**Comment by Iximiel** [comment]
That's clearer, thanks

I need #4 for the local run, I'm changing it to upload the extra md files

also #6 needs #4, so do not accept it

**Comment by gtribello** [comment]
@Iximiel I've dealt with the problem in `build_manual.py` and the CI is running again.  In other words, `build_manual.py` runs even if the plumed-tutorials website is not up.   Can you please look into the PR that you submitted again?  Please ensure that ALL the website pages are transferred to the `plumed-school.github.io` repo at the end of the workflow.  Accepting that PR messed up A LOT of things.  

Testing that the new workflow passes is not sufficient.  This is why it is difficult to work on this branch with PRs.  Only pushes to main on plumed-school trigger the second commit to `plumed-school.github.io`.  It would be really good if we had this setup so a push to any branch other than main did the following:

1. Run the workflow on plumed-school
2. Push the workflow to a branch called test on plumed-school.github.io
3. Compare the files in the test branch on plumed-school.github.io with the files in the master branch of plumed-school.github.io 

We would then have a mechanism for ensuring that changes to the code for building the site are not changing the site in a significant way.

**Comment by Iximiel** [comment]
I was about to write, because I don't understand where those .md files in the home of the repo are excluded/selected by the .ci/push, 'git grepping' for them brings only comments

>We would then have a mechanism for ensuring that changes to the code for building the site are not changing the site in a significant way.

I totally agree, maybe it is better to set up that before the re-revert of #4

**Comment by gtribello** [comment]
I don't understand why those .md files are excluded either.  The first thing I would check is whether there is something weird going on because there are separate copies of each of those files on the two replicas.

Yes, if you can, please set up the testing described above as part of a revised #4.

**Pull request merged**
